package org.test;

import java.util.HashMap;

import org.test.Elementos.et;

public class CreaCtaD {

	private static HashMap<String, Elementos> d;
	
	private static CreaCtaD self = null;

	protected CreaCtaD(){
		System.out.println("Entro aqui");
		d = new HashMap<String, Elementos>();
		
	}
	public static CreaCtaD Layout(){
		
		if (self == null){
			self = new CreaCtaD();
			self.addField("MAINFTM", 0, "MAINFTM", false, et.NUMBER);
			self.addField("MAINBTID", 0, "MAINBTID", false);
			self.addField("RESPONSE", 0, "RESPONSE", false, et.NUMBER);
			self.addField("USERID", 0, "USERID", false);
			self.addField("LANGUAGEID", 0, "LANGUAGEID", false);
			self.addField("BRANCHID", 0, "BRANCHID", false, et.NUMBER);
			self.addField("OFFICEID", 0, "OFFICEID", false, et.NUMBER);
			self.addField("DEPTOID", 0, "DEPTOID", false, et.NUMBER);
			self.addField("TERMINALID", 0, "TERMINALID", false);
			self.addField("MESSENGERID", 0, "MESSENGERID", false);
			self.addField("SESSIONKEY", 0, "SESSIONKEY", false);
			self.addField("EXTERNALREFERENCE", 0, "EXTERNALREFERENCE", false);
			self.addField("REFERENCEUSER", 0, "REFERENCEUSER", false);
			self.addField("PROCESSTYPE", 0, "PROCESSTYPE", false);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ID", 0, "ID.0", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PARENT", 0, "PARENT.0", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.MULTIVALUE", 0, "MULTIVALUE.0", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.REQUEST_ID", 0, "TREQ_LIABILITIE_ACCOUNT.REQUEST_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.REQUEST_SEQ", 0, "TREQ_LIABILITIE_ACCOUNT.REQUEST_SEQ", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_LINE_ID", 0, "TREQ_LIABILITIE_ACCOUNT.PRODUCT_LINE_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_ID", 0, "TREQ_LIABILITIE_ACCOUNT.PRODUCT_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACC_OFFICER_ID", 0, "TREQ_LIABILITIE_ACCOUNT.ACC_OFFICER_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BRANCH", 0, "TREQ_LIABILITIE_ACCOUNT.BRANCH", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_NAME", 0, "TREQ_LIABILITIE_ACCOUNT.ACCOUNT_NAME", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.AMOUNT", 0, "TREQ_LIABILITIE_ACCOUNT.AMOUNT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.CASH_AMOUNT", 0, "TREQ_LIABILITIE_ACCOUNT.CASH_AMOUNT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.CHECK_AMOUNT", 0, "TREQ_LIABILITIE_ACCOUNT.CHECK_AMOUNT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.TRANSFER_AMOUNT", 0, "TREQ_LIABILITIE_ACCOUNT.TRANSFER_AMOUNT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CAT", 0, "TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CAT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT", 0, "TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.CORE_REFERENCE", 0, "TREQ_LIABILITIE_ACCOUNT.CORE_REFERENCE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.RETENTION_STATEMENT", 0, "TREQ_LIABILITIE_ACCOUNT.RETENTION_STATEMENT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.RETENTION_BRANCH", 0, "TREQ_LIABILITIE_ACCOUNT.RETENTION_BRANCH", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CONCEPT", 0, "TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CONCEPT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE_CAT", 0, "TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE_CAT", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE", 0, "TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_SECOND_NAME", 0, "TREQ_LIABILITIE_ACCOUNT.ACCOUNT_SECOND_NAME", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_THIRD_NAME", 0, "TREQ_LIABILITIE_ACCOUNT.ACCOUNT_THIRD_NAME", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST", 0, "TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST_NUM", 0, "TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST_NUM", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.RECORD_NUMBER", 0, "TREQ_LIABILITIE_ACCOUNT.RECORD_NUMBER", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.I_USER_ID", 0, "TREQ_LIABILITIE_ACCOUNT.I_USER_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.I_DATE", 0, "TREQ_LIABILITIE_ACCOUNT.I_DATE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_USER_ID", 0, "TREQ_LIABILITIE_ACCOUNT.A_USER_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_DATE", 0, "TREQ_LIABILITIE_ACCOUNT.A_DATE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.AREA_DEF_ID", 0, "TREQ_LIABILITIE_ACCOUNT.AREA_DEF_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.AREA_ID", 0, "TREQ_LIABILITIE_ACCOUNT.AREA_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_COMPANY_ID", 0, "TREQ_LIABILITIE_ACCOUNT.A_COMPANY_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_SS_ID", 0, "TREQ_LIABILITIE_ACCOUNT.A_SS_I", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.CONTRACT_NUMBER", 0, "TREQ_LIABILITIE_ACCOUNT.CONTRACT_NUMBER", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PAYDET_TOTAL", 0, "TREQ_LIABILITIE_ACCOUNT.PAYDET_TOTAL", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_DET_ID", 0, "TREQ_LIABILITIE_ACCOUNT.PRODUCT_DET_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_SUBLINE", 0, "TREQ_LIABILITIE_ACCOUNT.PRODUCT_SUBLINE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.VALIDATE_PAYDET_TOTAL", 0, "TREQ_LIABILITIE_ACCOUNT.VALIDATE_PAYDET_TOTAL", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_TYPE", 0, "TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_TYPE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_ID", 0, "TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.CURRENCY", 0, "TREQ_LIABILITIE_ACCOUNT.CURRENCY", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_BRANCH_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_BRANCH_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICE_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_OFFICE_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_PRODUCT_CODE", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_PRODUCT_CODE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_STATUS", 0, "TREQ_LIABILITIE_ACCOUNT.ACCOUNT_STATUS", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_CATEGORY", 0, "TREQ_LIABILITIE_ACCOUNT.ACCOUNT_CATEGORY", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_BRANCH_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_BRANCH_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_OFFICE_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_OFFICE_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.ADDRESS", 0, "TREQ_LIABILITIE_ACCOUNT.ADDRESS", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_TYPE", 0, "TREQ_LIABILITIE_ACCOUNT.PERSON_TYPE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_SECURITY_LEVEL", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_SECURITY_LEVEL", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICER_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_OFFICER_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_REQUEST_ID", 0, "TREQ_LIABILITIE_ACCOUNT.FISA_REQUEST_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.SELLER_ONE_ID", 0, "TREQ_LIABILITIE_ACCOUNT.SELLER_ONE_ID", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.SELLRATE", 0, "TREQ_LIABILITIE_ACCOUNT.SELLRATE", true);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BUYRATE", 0, "TREQ_LIABILITIE_ACCOUNT.BUYRATE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.ID", 1, "ID.1", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PARENT", 1, "PARENT.1", true, et.NUMBER);
			self.addField("TREQ_LIABILITIE_PAYDET.MULTIVALUE", 1, "MULTIVALUE.1", true);
			self.addField("TREQ_LIABILITIE_PAYDET.REQUEST_ID", 1, "TREQ_LIABILITIE_PAYDET.REQUEST_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.REQUEST_SEQ", 1, "TREQ_LIABILITIE_PAYDET.REQUEST_SEQ", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_SEQ", 1, "TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_SEQ", true);
			self.addField("TREQ_LIABILITIE_PAYDET.BRANCH", 1, "TREQ_LIABILITIE_PAYDET.BRANCH", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_DATE", 1, "TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_DATE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_OFFICER", 1, "TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_OFFICER", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE_CAT", 1, "TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE_CAT", true);
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE", 1, "TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.AMOUNT", 1, "TREQ_LIABILITIE_PAYDET.AMOUNT", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY", 1, "TREQ_LIABILITIE_PAYDET.CURRENCY", true);
			self.addField("TREQ_LIABILITIE_PAYDET.DEST_MODULE", 1, "TREQ_LIABILITIE_PAYDET.DEST_MODULE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_PRICE", 1, "TREQ_LIABILITIE_PAYDET.CURRENCY_PRICE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CHARGE_CODE", 1, "TREQ_LIABILITIE_PAYDET.CHARGE_CODE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CHARGE_AMOUNT", 1, "TREQ_LIABILITIE_PAYDET.CHARGE_AMOUNT", true);
			self.addField("TREQ_LIABILITIE_PAYDET.RECORD_NUMBER", 1, "TREQ_LIABILITIE_PAYDET.RECORD_NUMBER", true);
			self.addField("TREQ_LIABILITIE_PAYDET.I_USER_ID", 1, "TREQ_LIABILITIE_PAYDET.I_USER_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.I_DATE", 1, "TREQ_LIABILITIE_PAYDET.I_DATE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.A_USER_ID", 1, "TREQ_LIABILITIE_PAYDET.A_USER_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.A_DATE", 1, "TREQ_LIABILITIE_PAYDET.A_DATE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.AREA_DEF_ID", 1, "TREQ_LIABILITIE_PAYDET.AREA_DEF_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.AREA_ID", 1, "TREQ_LIABILITIE_PAYDET.AREA_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.A_COMPANY_ID", 1, "TREQ_LIABILITIE_PAYDET.A_COMPANY_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.A_SS_ID", 1, "TREQ_LIABILITIE_PAYDET.A_SS_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.AVAILABLE_AMOUNT", 1, "TREQ_LIABILITIE_PAYDET.AVAILABLE_AMOUNT", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_BUY_PRICE", 1, "TREQ_LIABILITIE_PAYDET.CURRENCY_BUY_PRICE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_SELL_PRICE", 1, "TREQ_LIABILITIE_PAYDET.CURRENCY_SELL_PRICE", true);
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_BRANCH_ID", 1, "TREQ_LIABILITIE_PAYDET.FISA_BRANCH_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_OFFICE_ID", 1, "TREQ_LIABILITIE_PAYDET.FISA_OFFICE_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_MOD_ID", 1, "TREQ_LIABILITIE_PAYDET.FISA_MOD_ID", true);
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_MOD_DESTINY_ID", 1, "TREQ_LIABILITIE_PAYDET.FISA_MOD_DESTINY_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.ID", 2, "ID.2", true);
			self.addField("TREQ_LIABILITIE_SIGNER.PARENT", 2, "PARENT.2", true, et.NUMBER);
			self.addField("TREQ_LIABILITIE_SIGNER.MULTIVALUE", 2, "MULTIVALUE.2", true);
			self.addField("TREQ_LIABILITIE_SIGNER.REQUEST_ID", 2, "TREQ_LIABILITIE_SIGNER.REQUEST_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.REQUEST_SEQ", 2, "TREQ_LIABILITIE_SIGNER.REQUEST_SEQ", true);
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_SEQ", 2, "TREQ_LIABILITIE_SIGNER.SIGNATURE_SEQ", true);
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_TYPE", 2, "TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_TYPE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_ID", 2, "TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE_CAT", 2, "TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE_CAT", true);
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE", 2, "TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_NAME", 2, "TREQ_LIABILITIE_SIGNER.PERSON_NAME", true);
			self.addField("TREQ_LIABILITIE_SIGNER.HOLDER", 2, "TREQ_LIABILITIE_SIGNER.HOLDER", true);
			self.addField("TREQ_LIABILITIE_SIGNER.MAX_AMOUNT_AUTHORIZED", 2, "TREQ_LIABILITIE_SIGNER.MAX_AMOUNT_AUTHORIZED", true);
			self.addField("TREQ_LIABILITIE_SIGNER.EFFECTIVE_DATE", 2, "TREQ_LIABILITIE_SIGNER.EFFECTIVE_DATE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.EXPIRATION_DATE", 2, "TREQ_LIABILITIE_SIGNER.EXPIRATION_DATE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY_CAT", 2, "TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY_CAT", true);
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY", 2, "TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY", true);
			self.addField("TREQ_LIABILITIE_SIGNER.RECORD_NUMBER", 2, "TREQ_LIABILITIE_SIGNER.RECORD_NUMBER", true);
			self.addField("TREQ_LIABILITIE_SIGNER.I_USER_ID", 2, "TREQ_LIABILITIE_SIGNER.I_USER_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.I_DATE", 2, "TREQ_LIABILITIE_SIGNER.I_DATE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.A_USER_ID", 2, "TREQ_LIABILITIE_SIGNER.A_USER_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.A_DATE", 2, "TREQ_LIABILITIE_SIGNER.A_DATE", true);
			self.addField("TREQ_LIABILITIE_SIGNER.AREA_DEF_ID", 2, "TREQ_LIABILITIE_SIGNER.AREA_DEF_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.AREA_ID", 2, "TREQ_LIABILITIE_SIGNER.AREA_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.A_COMPANY_ID", 2, "TREQ_LIABILITIE_SIGNER.A_COMPANY_ID", true);
			self.addField("TREQ_LIABILITIE_SIGNER.A_SS_ID", 2, "TREQ_LIABILITIE_SIGNER.A_SS_ID", true);
			self.addField("TREQ_CUS_PRD_REL.ID", 3, "ID.3", true);
			self.addField("TREQ_CUS_PRD_REL.PARENT", 3, "PARENT.3", true, et.NUMBER);
			self.addField("TREQ_CUS_PRD_REL.MULTIVALUE", 3, "MULTIVALUE.3", true);
			self.addField("TREQ_CUS_PRD_REL.REQUEST_ID", 3, "TREQ_CUS_PRD_REL.REQUEST_ID", true);
			self.addField("TREQ_CUS_PRD_REL.CUSTOMER_SEQ", 3, "TREQ_CUS_PRD_REL.CUSTOMER_SEQ", true);
			self.addField("TREQ_CUS_PRD_REL.RELATION_ID", 3, "TREQ_CUS_PRD_REL.RELATION_ID", true);
			self.addField("TREQ_CUS_PRD_REL.CORE_CLIENT_ID", 3, "TREQ_CUS_PRD_REL.CORE_CLIENT_ID", true);
			self.addField("TREQ_CUS_PRD_REL.PERCENTAGE", 3, "TREQ_CUS_PRD_REL.PERCENTAGE", true);
			self.addField("TREQ_CUS_PRD_REL.RELATION", 3, "TREQ_CUS_PRD_REL.RELATION", true);
			self.addField("TREQ_CUS_PRD_REL.RELATION_ORDER", 3, "TREQ_CUS_PRD_REL.RELATION_ORDER", true);
			self.addField("TREQ_CUS_PRD_REL.ADDRESS_ID", 3, "TREQ_CUS_PRD_REL.ADDRESS_ID", true);
			
		}
		System.out.println("NO NULLLLLLLLLLLLLLLLLLLLLLLL");
		return self;
	}
	public static HashMap<String, Elementos> getLayout(){
		return d;
	}
	
	private void addField(String id, int indiceArray, String position, Boolean isArray){
		d.put(id, new Elementos(indiceArray, position, isArray));
	}
	
	private void addField(String id, int indiceArray, String position, Boolean isArray, et tipoDato){
		d.put(id, new Elementos(indiceArray, position, isArray));
	}	
}
