package org.test;

import java.util.HashMap;

public class CreaCta {

	private static HashMap<String, Parametros> d;
	
	private static CreaCta self = null;

	protected CreaCta(){
		System.out.println("Entro aqui");
		d = new HashMap<String, Parametros>();
		
	}
	public static CreaCta Layout(){
		
		if (self == null){
			self = new CreaCta();
			self.addField("pni_currposition", "pni_currposition", 1);
			self.addField("MAINFTM", "FM.MAINFTM", "OTR_FM", 1);
			self.addField("MAINBTID", "FM.MAINBTID", "OTR_FM");
			self.addField("RESPONSE", "FM.RESPONSE", "OTR_FM");
			self.addField("USERID", "FM.HEADER.USERID", "OTR_HEADER");
			self.addField("LANGUAGEID", "FM.HEADER.LANGUAGEID", "OTR_HEADER", "es");
			self.addField("BRANCHID", "FM.HEADER.BRANCHID", "OTR_HEADER");
			self.addField("OFFICEID", "FM.HEADER.OFFICEID", "OTR_HEADER");
			self.addField("DEPTOID", "FM.HEADER.DEPTOID", "OTR_HEADER");
			self.addField("TERMINALID", "FM.HEADER.TERMINALID", "OTR_HEADER");
			self.addField("MESSENGERID", "FM.HEADER.MESSENGERID", "OTR_HEADER");
			self.addField("SESSIONKEY", "FM.HEADER.SESSIONKEY", "OTR_HEADER");
			self.addField("EXTERNALREFERENCE", "FM.HEADER.EXTERNALREFERENCE", "OTR_HEADER");
			self.addField("REFERENCEUSER", "FM.HEADER.REFERENCEUSER", "OTR_HEADER");
			self.addField("PROCESSTYPE", "FM.HEADER.PROCESSTYPE", "OTR_HEADER","TXN");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ID", "FM.FMT.TAB.0.ID", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PARENT", "FM.FMT.TAB.0.PARENT", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_ACCOUNT.MULTIVALUE", "FM.FMT.TAB.0.MULTIVALUE", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_ACCOUNT.REQUEST_ID", "FM.FMT.TAB.0.REC.FIELD.REQUEST_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.REQUEST_SEQ", "FM.FMT.TAB.0.REC.FIELD.REQUEST_SEQ", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_LINE_ID", "FM.FMT.TAB.0.REC.FIELD.PRODUCT_LINE_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_ID", "FM.FMT.TAB.0.REC.FIELD.PRODUCT_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACC_OFFICER_ID", "FM.FMT.TAB.0.REC.FIELD.ACC_OFFICER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.BRANCH", "FM.FMT.TAB.0.REC.FIELD.BRANCH", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_NAME", "FM.FMT.TAB.0.REC.FIELD.ACCOUNT_NAME", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.AMOUNT", "FM.FMT.TAB.0.REC.FIELD.AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.CASH_AMOUNT", "FM.FMT.TAB.0.REC.FIELD.CASH_AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.CHECK_AMOUNT", "FM.FMT.TAB.0.REC.FIELD.CHECK_AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.TRANSFER_AMOUNT", "FM.FMT.TAB.0.REC.FIELD.TRANSFER_AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CAT", "FM.FMT.TAB.0.REC.FIELD.BANK_DRAFT_CAT", "OTR_FIELD", 59);
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT", "FM.FMT.TAB.0.REC.FIELD.BANK_DRAFT", "OTR_FIELD","1");
			self.addField("TREQ_LIABILITIE_ACCOUNT.CORE_REFERENCE", "FM.FMT.TAB.0.REC.FIELD.CORE_REFERENCE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.RETENTION_STATEMENT", "FM.FMT.TAB.0.REC.FIELD.RETENTION_STATEMENT", "OTR_FIELD","N");
			self.addField("TREQ_LIABILITIE_ACCOUNT.RETENTION_BRANCH", "FM.FMT.TAB.0.REC.FIELD.RETENTION_BRANCH", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CONCEPT", "FM.FMT.TAB.0.REC.FIELD.BANK_DRAFT_CONCEPT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE_CAT", "FM.FMT.TAB.0.REC.FIELD.WITHDRAWAL_FILE_CAT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE", "FM.FMT.TAB.0.REC.FIELD.WITHDRAWAL_FILE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_SECOND_NAME", "FM.FMT.TAB.0.REC.FIELD.ACCOUNT_SECOND_NAME", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_THIRD_NAME", "FM.FMT.TAB.0.REC.FIELD.ACCOUNT_THIRD_NAME", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST", "FM.FMT.TAB.0.REC.FIELD.DEBIT_CARD_REQUEST", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST_NUM", "FM.FMT.TAB.0.REC.FIELD.DEBIT_CARD_REQUEST_NUM", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.RECORD_NUMBER", "FM.FMT.TAB.0.REC.FIELD.RECORD_NUMBER", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.I_USER_ID", "FM.FMT.TAB.0.REC.FIELD.I_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.I_DATE", "FM.FMT.TAB.0.REC.FIELD.I_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_USER_ID", "FM.FMT.TAB.0.REC.FIELD.A_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_DATE", "FM.FMT.TAB.0.REC.FIELD.A_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.AREA_DEF_ID", "FM.FMT.TAB.0.REC.FIELD.AREA_DEF_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.AREA_ID", "FM.FMT.TAB.0.REC.FIELD.AREA_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_COMPANY_ID", "FM.FMT.TAB.0.REC.FIELD.A_COMPANY_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.A_SS_ID", "FM.FMT.TAB.0.REC.FIELD.A_SS_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.CONTRACT_NUMBER", "FM.FMT.TAB.0.REC.FIELD.CONTRACT_NUMBER", "OTR_FIELD", "9999");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PAYDET_TOTAL", "FM.FMT.TAB.0.REC.FIELD.PAYDET_TOTAL", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_DET_ID", "FM.FMT.TAB.0.REC.FIELD.PRODUCT_DET_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PRODUCT_SUBLINE", "FM.FMT.TAB.0.REC.FIELD.PRODUCT_SUBLINE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.VALIDATE_PAYDET_TOTAL", "FM.FMT.TAB.0.REC.FIELD.VALIDATE_PAYDET_TOTAL", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_TYPE", "FM.FMT.TAB.0.REC.FIELD.PERSON_LEGAL_TYPE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_ID", "FM.FMT.TAB.0.REC.FIELD.PERSON_LEGAL_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.CURRENCY", "FM.FMT.TAB.0.REC.FIELD.CURRENCY", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_BRANCH_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_BRANCH_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICE_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_OFFICE_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_PRODUCT_CODE", "FM.FMT.TAB.0.REC.FIELD.FISA_PRODUCT_CODE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_STATUS", "FM.FMT.TAB.0.REC.FIELD.ACCOUNT_STATUS", "OTR_FIELD","2");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_CATEGORY", "FM.FMT.TAB.0.REC.FIELD.ACCOUNT_CATEGORY", "OTR_FIELD","A");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_BRANCH_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_RETENTION_BRANCH_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_OFFICE_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_RETENTION_OFFICE_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.ADDRESS", "FM.FMT.TAB.0.REC.FIELD.ADDRESS", "OTR_FIELD","1");
			self.addField("TREQ_LIABILITIE_ACCOUNT.PERSON_TYPE", "FM.FMT.TAB.0.REC.FIELD.PERSON_TYPE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_SECURITY_LEVEL", "FM.FMT.TAB.0.REC.FIELD.FISA_SECURITY_LEVEL", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICER_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_OFFICER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.FISA_REQUEST_ID", "FM.FMT.TAB.0.REC.FIELD.FISA_REQUEST_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.SELLER_ONE_ID", "FM.FMT.TAB.0.REC.FIELD.SELLER_ONE_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.SELLRATE", "FM.FMT.TAB.0.REC.FIELD.SELLRATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_ACCOUNT.BUYRATE", "FM.FMT.TAB.0.REC.FIELD.BUYRATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.ID", "FM.FMT.TAB.1.ID", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_PAYDET.PARENT", "FM.FMT.TAB.1.PARENT", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_PAYDET.MULTIVALUE", "FM.FMT.TAB.1.MULTIVALUE", "OTR_TAB");
			self.addField("TREQ_LIABILITIE_PAYDET.REQUEST_ID", "FM.FMT.TAB.1.REC.FIELD.REQUEST_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.REQUEST_SEQ", "FM.FMT.TAB.1.REC.FIELD.REQUEST_SEQ", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_SEQ", "FM.FMT.TAB.1.REC.FIELD.PAYMENT_DETAIL_SEQ", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.BRANCH", "FM.FMT.TAB.1.REC.FIELD.BRANCH", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_DATE", "FM.FMT.TAB.1.REC.FIELD.PAYMENT_DETAIL_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_OFFICER", "FM.FMT.TAB.1.REC.FIELD.PAYMENT_DETAIL_OFFICER", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE_CAT", "FM.FMT.TAB.1.REC.FIELD.PAYMENT_DETAIL_TYPE_CAT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE", "FM.FMT.TAB.1.REC.FIELD.PAYMENT_DETAIL_TYPE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.AMOUNT", "FM.FMT.TAB.1.REC.FIELD.AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY", "FM.FMT.TAB.1.REC.FIELD.CURRENCY", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.DEST_MODULE", "FM.FMT.TAB.1.REC.FIELD.DEST_MODULE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_PRICE", "FM.FMT.TAB.1.REC.FIELD.CURRENCY_PRICE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CHARGE_CODE", "FM.FMT.TAB.1.REC.FIELD.CHARGE_CODE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CHARGE_AMOUNT", "FM.FMT.TAB.1.REC.FIELD.CHARGE_AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.RECORD_NUMBER", "FM.FMT.TAB.1.REC.FIELD.RECORD_NUMBER", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.I_USER_ID", "FM.FMT.TAB.1.REC.FIELD.I_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.I_DATE", "FM.FMT.TAB.1.REC.FIELD.I_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.A_USER_ID", "FM.FMT.TAB.1.REC.FIELD.A_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.A_DATE", "FM.FMT.TAB.1.REC.FIELD.A_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.AREA_DEF_ID", "FM.FMT.TAB.1.REC.FIELD.AREA_DEF_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.AREA_ID", "FM.FMT.TAB.1.REC.FIELD.AREA_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.A_COMPANY_ID", "FM.FMT.TAB.1.REC.FIELD.A_COMPANY_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.A_SS_ID", "FM.FMT.TAB.1.REC.FIELD.A_SS_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.AVAILABLE_AMOUNT", "FM.FMT.TAB.1.REC.FIELD.AVAILABLE_AMOUNT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_BUY_PRICE", "FM.FMT.TAB.1.REC.FIELD.CURRENCY_BUY_PRICE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.CURRENCY_SELL_PRICE", "FM.FMT.TAB.1.REC.FIELD.CURRENCY_SELL_PRICE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_BRANCH_ID", "FM.FMT.TAB.1.REC.FIELD.FISA_BRANCH_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_OFFICE_ID", "FM.FMT.TAB.1.REC.FIELD.FISA_OFFICE_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_MOD_ID", "FM.FMT.TAB.1.REC.FIELD.FISA_MOD_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_PAYDET.FISA_MOD_DESTINY_ID", "FM.FMT.TAB.1.REC.FIELD.FISA_MOD_DESTINY_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.ID", "FM.FMT.TAB.2.ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.PARENT", "FM.FMT.TAB.2.PARENT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.MULTIVALUE", "FM.FMT.TAB.2.MULTIVALUE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.REQUEST_ID", "FM.FMT.TAB.2.REC.FIELD.REQUEST_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.REQUEST_SEQ", "FM.FMT.TAB.2.REC.FIELD.REQUEST_SEQ", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_SEQ", "FM.FMT.TAB.2.REC.FIELD.SIGNATURE_SEQ", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_TYPE", "FM.FMT.TAB.2.REC.FIELD.PERSON_LEGAL_TYPE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_ID", "FM.FMT.TAB.2.REC.FIELD.PERSON_LEGAL_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE_CAT", "FM.FMT.TAB.2.REC.FIELD.SIGNATURE_TYPE_CAT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE", "FM.FMT.TAB.2.REC.FIELD.SIGNATURE_TYPE", "OTR_FIELD","F");
			self.addField("TREQ_LIABILITIE_SIGNER.PERSON_NAME", "FM.FMT.TAB.2.REC.FIELD.PERSON_NAME", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.HOLDER", "FM.FMT.TAB.2.REC.FIELD.HOLDER", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.MAX_AMOUNT_AUTHORIZED", "FM.FMT.TAB.2.REC.FIELD.MAX_AMOUNT_AUTHORIZED", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.EFFECTIVE_DATE", "FM.FMT.TAB.2.REC.FIELD.EFFECTIVE_DATE", "OTR_FIELD", "sysdate"); // <======= ENVIAR SYSDATE
			self.addField("TREQ_LIABILITIE_SIGNER.EXPIRATION_DATE", "FM.FMT.TAB.2.REC.FIELD.EXPIRATION_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY_CAT", "FM.FMT.TAB.2.REC.FIELD.SIGNATURE_CATEGORY_CAT", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY", "FM.FMT.TAB.2.REC.FIELD.SIGNATURE_CATEGORY", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.RECORD_NUMBER", "FM.FMT.TAB.2.REC.FIELD.RECORD_NUMBER", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.I_USER_ID", "FM.FMT.TAB.2.REC.FIELD.I_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.I_DATE", "FM.FMT.TAB.2.REC.FIELD.I_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.A_USER_ID", "FM.FMT.TAB.2.REC.FIELD.A_USER_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.A_DATE", "FM.FMT.TAB.2.REC.FIELD.A_DATE", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.AREA_DEF_ID", "FM.FMT.TAB.2.REC.FIELD.AREA_DEF_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.AREA_ID", "FM.FMT.TAB.2.REC.FIELD.AREA_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.A_COMPANY_ID", "FM.FMT.TAB.2.REC.FIELD.A_COMPANY_ID", "OTR_FIELD");
			self.addField("TREQ_LIABILITIE_SIGNER.A_SS_ID", "FM.FMT.TAB.2.REC.FIELD.A_SS_ID", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.ID", "FM.FMT.TAB.3.ID", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.PARENT", "FM.FMT.TAB.3.PARENT", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.MULTIVALUE", "FM.FMT.TAB.3.MULTIVALUE", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.REQUEST_ID", "FM.FMT.TAB.3.REC.FIELD.REQUEST_ID", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.CUSTOMER_SEQ", "FM.FMT.TAB.3.REC.FIELD.CUSTOMER_SEQ", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.RELATION_ID", "FM.FMT.TAB.3.REC.FIELD.RELATION_ID", "OTR_FIELD",1);
			self.addField("TREQ_CUS_PRD_REL.CORE_CLIENT_ID", "FM.FMT.TAB.3.REC.FIELD.CORE_CLIENT_ID", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.PERCENTAGE", "FM.FMT.TAB.3.REC.FIELD.PERCENTAGE", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.RELATION", "FM.FMT.TAB.3.REC.FIELD.RELATION", "OTR_FIELD");
			self.addField("TREQ_CUS_PRD_REL.RELATION_ORDER", "FM.FMT.TAB.3.REC.FIELD.RELATION_ORDER", "OTR_FIELD",1);
			self.addField("TREQ_CUS_PRD_REL.ADDRESS_ID", "FM.FMT.TAB.3.REC.FIELD.ADDRESS_ID", "OTR_FIELD",1);
			
		}
		System.out.println("NO NULLLLLLLLLLLLLLLLLLLLLLLL");
		return self;
	}
	public static HashMap<String, Parametros> getLayout(){
		return d;
	}
	
	private void addField(String id, String ide, String tipo, Object def){
		d.put(id, new Parametros(ide, tipo, def));
	}
	private void addField(String id, String ide, String tipo){
		d.put(id, new Parametros(ide, tipo));
	}	
	private void addField(String id, String ide, Object val){
		d.put(id, new Parametros(ide, val));
	}		
}
