package org.test;

import java.util.HashMap;

public class Entrada {

	private static Entrada instance = null;
	private static HashMap<String, Object> d = null;

	public  Entrada getInstance() {
		if (instance == null) {
			instance = new Entrada();
		}
		return instance;
	}

	protected Entrada() {
	}

	public  static HashMap<String, Object> getMetaData() {
		if (d == null) {
			d = new HashMap<String, Object>();
			d.put("TOKEN", "A");
			d.put("pni_currposition", "A");
			d.put("MAINFTM", 100);
			d.put("MAINBTID", "A");
			d.put("RESPONSE", 5);
			d.put("USERID", "A");
			d.put("LANGUAGEID", "A");
			d.put("BRANCHID", 1);
			d.put("OFFICEID", 2);
			d.put("DEPTOID", 3);
			d.put("TERMINALID", "A");
			d.put("MESSENGERID", "A");
			d.put("SESSIONKEY", "A");
			d.put("EXTERNALREFERENCE", "A");
			d.put("REFERENCEUSER", "A");
			d.put("PROCESSTYPE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PARENT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.MULTIVALUE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.REQUEST_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.REQUEST_SEQ", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PRODUCT_LINE_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PRODUCT_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACC_OFFICER_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.BRANCH", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_NAME", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.AMOUNT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.CASH_AMOUNT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.CHECK_AMOUNT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.TRANSFER_AMOUNT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CAT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.CORE_REFERENCE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.RETENTION_STATEMENT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.RETENTION_BRANCH", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.BANK_DRAFT_CONCEPT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE_CAT", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.WITHDRAWAL_FILE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_SECOND_NAME", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_THIRD_NAME", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.DEBIT_CARD_REQUEST_NUM", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.RECORD_NUMBER", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.I_USER_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.I_DATE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.A_USER_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.A_DATE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.AREA_DEF_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.AREA_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.A_COMPANY_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.A_SS_ID", 1);
			d.put("TREQ_LIABILITIE_ACCOUNT.CONTRACT_NUMBER", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PAYDET_TOTAL", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PRODUCT_DET_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PRODUCT_SUBLINE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.VALIDATE_PAYDET_TOTAL", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_TYPE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PERSON_LEGAL_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.CURRENCY", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_BRANCH_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICE_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_PRODUCT_CODE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_STATUS", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ACCOUNT_CATEGORY", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_BRANCH_ID", 5999);
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_RETENTION_OFFICE_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.ADDRESS", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.PERSON_TYPE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_SECURITY_LEVEL", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_OFFICER_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.FISA_REQUEST_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.SELLER_ONE_ID", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.SELLRATE", "A");
			d.put("TREQ_LIABILITIE_ACCOUNT.BUYRATE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PARENT", "A");
			d.put("TREQ_LIABILITIE_PAYDET.MULTIVALUE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.REQUEST_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.REQUEST_SEQ", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_SEQ", 5555);
			d.put("TREQ_LIABILITIE_PAYDET.BRANCH", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_DATE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_OFFICER", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE_CAT", "A");
			d.put("TREQ_LIABILITIE_PAYDET.PAYMENT_DETAIL_TYPE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.AMOUNT", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CURRENCY", "A");
			d.put("TREQ_LIABILITIE_PAYDET.DEST_MODULE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CURRENCY_PRICE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CHARGE_CODE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CHARGE_AMOUNT", "A");
			d.put("TREQ_LIABILITIE_PAYDET.RECORD_NUMBER", "A");
			d.put("TREQ_LIABILITIE_PAYDET.I_USER_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.I_DATE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.A_USER_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.A_DATE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.AREA_DEF_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.AREA_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.A_COMPANY_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.A_SS_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.AVAILABLE_AMOUNT", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CURRENCY_BUY_PRICE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.CURRENCY_SELL_PRICE", "A");
			d.put("TREQ_LIABILITIE_PAYDET.FISA_BRANCH_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.FISA_OFFICE_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.FISA_MOD_ID", "A");
			d.put("TREQ_LIABILITIE_PAYDET.FISA_MOD_DESTINY_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.PARENT", "A");
			d.put("TREQ_LIABILITIE_SIGNER.MULTIVALUE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.REQUEST_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.REQUEST_SEQ", "A");
			d.put("TREQ_LIABILITIE_SIGNER.SIGNATURE_SEQ", "A");
			d.put("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_TYPE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.PERSON_LEGAL_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE_CAT", "A");
			d.put("TREQ_LIABILITIE_SIGNER.SIGNATURE_TYPE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.PERSON_NAME", "A");
			d.put("TREQ_LIABILITIE_SIGNER.HOLDER", "A");
			d.put("TREQ_LIABILITIE_SIGNER.MAX_AMOUNT_AUTHORIZED", "A");
			d.put("TREQ_LIABILITIE_SIGNER.EFFECTIVE_DATE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.EXPIRATION_DATE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY_CAT", "A");
			d.put("TREQ_LIABILITIE_SIGNER.SIGNATURE_CATEGORY", "A");
			d.put("TREQ_LIABILITIE_SIGNER.RECORD_NUMBER", "A");
			d.put("TREQ_LIABILITIE_SIGNER.I_USER_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.I_DATE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.A_USER_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.A_DATE", "A");
			d.put("TREQ_LIABILITIE_SIGNER.AREA_DEF_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.AREA_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.A_COMPANY_ID", "A");
			d.put("TREQ_LIABILITIE_SIGNER.A_SS_ID", "A");
			d.put("TREQ_CUS_PRD_REL.ID", "A");
			d.put("TREQ_CUS_PRD_REL.PARENT", "A");
			d.put("TREQ_CUS_PRD_REL.MULTIVALUE", "A");
			d.put("TREQ_CUS_PRD_REL.REQUEST_ID", "A");
			d.put("TREQ_CUS_PRD_REL.CUSTOMER_SEQ", "A");
			d.put("TREQ_CUS_PRD_REL.RELATION_ID", "A");
			d.put("TREQ_CUS_PRD_REL.CORE_CLIENT_ID", "A");
			d.put("TREQ_CUS_PRD_REL.PERCENTAGE", "A");
			d.put("TREQ_CUS_PRD_REL.RELATION", "A");
			d.put("TREQ_CUS_PRD_REL.RELATION_ORDER", "A");
			d.put("TREQ_CUS_PRD_REL.ADDRESS_ID", "A");
		}
		return d;

	}

}
